[patch.crates-io.rclrs]
path = "/home/hiro/rust_ws/src/install/rclrs/share/rclrs/rust"

[patch.crates-io.test_msgs]
path = "/home/hiro/rust_ws/src/install/test_msgs/share/test_msgs/rust"

[patch.crates-io.rosgraph_msgs]
path = "/home/hiro/rust_ws/src/install/rosgraph_msgs/share/rosgraph_msgs/rust"

[patch.crates-io.rcl_interfaces]
path = "/home/hiro/rust_ws/src/install/rcl_interfaces/share/rcl_interfaces/rust"

[patch.crates-io.action_msgs]
path = "/home/hiro/rust_ws/src/install/action_msgs/share/action_msgs/rust"

[patch.crates-io.unique_identifier_msgs]
path = "/home/hiro/rust_ws/src/install/unique_identifier_msgs/share/unique_identifier_msgs/rust"

[patch.crates-io.rclrs_example_msgs]
path = "/home/hiro/rust_ws/src/install/rclrs_example_msgs/share/rclrs_example_msgs/rust"

[patch.crates-io.builtin_interfaces]
path = "/home/hiro/rust_ws/src/install/builtin_interfaces/share/builtin_interfaces/rust"

[patch.crates-io.rosidl_runtime_rs]
path = "/home/hiro/rust_ws/src/install/rosidl_runtime_rs/share/rosidl_runtime_rs/rust"

[patch.crates-io.std_msgs]
path = "/home/hiro/rust_ws/src/install/std_msgs/share/std_msgs/rust"

[patch.crates-io.example_interfaces]
path = "/home/hiro/rust_ws/src/install/example_interfaces/share/example_interfaces/rust"
