[package]
name = "test_msgs"
version = "1.2.1"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.4"
serde = { version = "1", optional = true, features = ["derive"] }
serde-big-array = { version = "0.5.1", optional = true }
builtin_interfaces = "*"
unique_identifier_msgs = "*"
action_msgs = "*"

[features]
serde = ['dep:serde', 'dep:serde-big-array', 'rosidl_runtime_rs/serde', 'builtin_interfaces/serde', 'unique_identifier_msgs/serde', 'action_msgs/serde']
